```yaml id="4f3im0"
name: MasterDnsVPN Persistent Deploy (Localtonet Fixed)

on:
  workflow_dispatch:

  schedule:
    # هر3 ساعت
    - cron: '0 */3 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 355

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Free Port 53 & Install Tools
        run: |
          sudo systemctl disable --now systemd-resolved || true

          sudo apt update

          sudo apt install -y \
            bind9 \
            curl \
            wget \
            unzip
```
