name: Ghost Bridge Operational
on:
  workflow_dispatch:

jobs:
  establish-bridge:
    runs-on: ubuntu-latest
    steps:
      - name: TCP Connectivity Check
        run: |
          # استفاده از nc (netcat) برای چک کردن باز بودن پورت TCP در سرور ایران [285، 522]
          nc -zv -w 5 87.107.12.8 2333 || echo "Port is CLOSED or Filtered"
